### PR TITLE
Fix compilation error if #define USE_FAT 0

### LINKED ISSUE #51: Compilation fails if FAT is turned off
A bug introduced in https://github.com/adafruit/uf2-samdx1/commit/17cf5763a98e04b40e747d8a8971e030ee0fb4f4#diff-3fe0a6c01ab9fbe7bdf42e7ee8a23c07 breaks compilation if FAT support is optioned off in uf2.h

The fix is trivial, this is mostly a placeholder on which for me to base a pull request momentarily

### PR DESCRIPTION
**Pull request by alexwhittemore**
NUM_DIRENTRIES is undefined if USE_FAT 0. I'm not quite sure why more of fat.c isn't excluded if USE_FAT 0, but this is the easy way to fix that one particular issue with minimal impact. Fix #51

### CODE REVIEW

**Comment by alexwhittemore** [comment]
>I'm not quite sure why more of fat.c isn't excluded if USE_FAT 0

To that point - any thoughts on why this is the case? Maybe there's something to be optimized here. I'd say I'll try to look into it and see if more can be optimized out, but I'm afraid I don't understand the architecture well enough to meddle that deeply.
